name: skeleton_project
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  intl: ^0.20.2
  freezed: ^3.1.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  easy_localization: ^3.0.7+1
  go_router: ^16.0.0
  # google_mobile_ads: ^6.0.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  json_serializable: ^6.9.5
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

# flutter_icons:
#   android: true
#   ios: true
#   image_path: "assets/images/icon.png"
#   adaptive_icon_background: "#F44336"
#   adaptive_icon_foreground: "assets/images/icon.png"
# To generate icons:
#  dart run flutter_launcher_icons:main

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/png/flags/
    - assets/png/
    - assets/svg/
